name: test2

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:          
          fetch-depth: 0

      - name: Docker for newman
        run: |
          docker run -v $(pwd)/api-tests2:/etc/newman -t postman/newman:latest run "test.json" --reporters="cli" -x
