name: User service workflow

on:
  push:
    branches:
      - master
    paths:
      - 'user_service/**'

jobs:
  deploy-user-service:
    uses: ./.github/workflows/deploy.yml
  x:
    runs-on: ubuntu-latest
    # steps:
      # Additional step specific for this service
